from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import JSON, Boolean, DateTime, Enum, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin
from app.models.enums import (
    CampaignRunStatus,
    CampaignStatus,
    CampaignType,
    Channel,
    ConnectionStatus,
    ConsentStatus,
    DeliveryStatus,
    DifficultyLevel,
    DomainKind,
    DomainPurpose,
    EmailProviderKind,
    EmployeeStatus,
    EventType,
    MediaAssetKind,
    MediaAssetStatus,
    MediaModality,
    OutboxStatus,
    PersonaStatus,
    ReportingIdentityMode,
    ScenarioStatus,
    SuppressionReason,
    TrainingAssignmentStatus,
    UserRole,
    VerificationStatus,
)
from app.models.types import EncryptedString


class Organization(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "organizations"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    slug: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    timezone: Mapped[str] = mapped_column(String(64), default="UTC")
    retention_days: Mapped[int] = mapped_column(Integer, default=365)
    privacy_notice: Mapped[str] = mapped_column(Text, default="Training and security awareness platform.")
    reporting_identity_mode: Mapped[ReportingIdentityMode] = mapped_column(
        Enum(ReportingIdentityMode), default=ReportingIdentityMode.PSEUDONYMOUS, nullable=False
    )
    suspended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    email_provider_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    email_provider_mode: Mapped[str] = mapped_column(String(32), default="sandbox")
    smtp_host: Mapped[str | None] = mapped_column(String(255))
    smtp_port: Mapped[int] = mapped_column(Integer, default=587)
    smtp_username: Mapped[str | None] = mapped_column(String(255))
    smtp_password: Mapped[str | None] = mapped_column(EncryptedString(1024))
    smtp_from_email: Mapped[str | None] = mapped_column(String(255))
    smtp_sender_name: Mapped[str | None] = mapped_column(String(255))
    smtp_recipient_allowlist: Mapped[list[str]] = mapped_column(JSON, default=list)

    sms_provider_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    sms_provider_mode: Mapped[str] = mapped_column(String(32), default="sandbox")
    sms_api_base_url: Mapped[str | None] = mapped_column(String(512))
    sms_account_sid: Mapped[str | None] = mapped_column(String(255))
    sms_auth_token: Mapped[str | None] = mapped_column(EncryptedString(1024))
    sms_from_number: Mapped[str | None] = mapped_column(String(64))
    sms_recipient_allowlist: Mapped[list[str]] = mapped_column(JSON, default=list)

    voice_provider_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    voice_provider_mode: Mapped[str] = mapped_column(String(32), default="simulator")
    voice_api_base_url: Mapped[str | None] = mapped_column(String(512))
    voice_account_sid: Mapped[str | None] = mapped_column(String(255))
    voice_auth_token: Mapped[str | None] = mapped_column(EncryptedString(1024))
    voice_from_number: Mapped[str | None] = mapped_column(String(64))
    voice_recipient_allowlist: Mapped[list[str]] = mapped_column(JSON, default=list)

    #: Synthetic-media impersonation is opt-in per organization and always requires a
    #: registered, consented persona before a scenario can be generated.
    impersonation_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    impersonation_disclosure_text: Mapped[str] = mapped_column(
        Text,
        default=(
            "Simulated synthetic media generated by BreachSim for authorized security "
            "awareness training. No real person was recorded, cloned, or published."
        ),
    )

    users: Mapped[list["User"]] = relationship(back_populates="organization")
    departments: Mapped[list["Department"]] = relationship(back_populates="organization")
    employees: Mapped[list["Employee"]] = relationship(back_populates="organization")
    domains: Mapped[list["OrganizationDomain"]] = relationship(
        back_populates="organization", cascade="all, delete-orphan"
    )
    branding: Mapped["OrganizationBranding | None"] = relationship(
        back_populates="organization", cascade="all, delete-orphan", uselist=False
    )
    email_connections: Mapped[list["EmailConnection"]] = relationship(
        back_populates="organization", cascade="all, delete-orphan"
    )


class OrganizationDomain(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "organization_domains"
    __table_args__ = (
        UniqueConstraint("hostname", "purpose", name="uq_domain_hostname_purpose"),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    hostname: Mapped[str] = mapped_column(String(253), nullable=False, index=True)
    purpose: Mapped[DomainPurpose] = mapped_column(Enum(DomainPurpose), nullable=False, index=True)
    kind: Mapped[DomainKind] = mapped_column(Enum(DomainKind), default=DomainKind.CUSTOM, nullable=False)
    status: Mapped[VerificationStatus] = mapped_column(
        Enum(VerificationStatus), default=VerificationStatus.PENDING, nullable=False, index=True
    )
    verification_token_hash: Mapped[str | None] = mapped_column(String(64))
    dns_instructions: Mapped[dict] = mapped_column(JSON, default=dict)
    validation_error: Mapped[str | None] = mapped_column(Text)
    is_primary: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    frontdoor_domain_id: Mapped[str | None] = mapped_column(String(255))
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    deactivated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    organization: Mapped["Organization"] = relationship(back_populates="domains")


class OrganizationBranding(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "organization_branding"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("organizations.id"), nullable=False, unique=True, index=True
    )
    logo_url: Mapped[str | None] = mapped_column(String(1024))
    primary_color: Mapped[str] = mapped_column(String(7), default="#173B73", nullable=False)
    accent_color: Mapped[str] = mapped_column(String(7), default="#175CD3", nullable=False)
    sender_name: Mapped[str] = mapped_column(String(255), default="Security Awareness", nullable=False)
    legal_footer: Mapped[str] = mapped_column(
        Text, default="Authorized security-awareness simulation.", nullable=False
    )
    approved_template_ids: Mapped[list[str]] = mapped_column(JSON, default=list)

    organization: Mapped["Organization"] = relationship(back_populates="branding")


class EmailConnection(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "email_connections"
    __table_args__ = (
        UniqueConstraint("organization_id", "provider", "sender_email", name="uq_org_provider_sender"),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    provider: Mapped[EmailProviderKind] = mapped_column(Enum(EmailProviderKind), nullable=False, index=True)
    display_name: Mapped[str] = mapped_column(String(255), nullable=False)
    customer_tenant_id: Mapped[str | None] = mapped_column(String(255))
    sender_email: Mapped[str] = mapped_column(String(320), nullable=False)
    sender_name: Mapped[str] = mapped_column(String(255), nullable=False)
    credential_secret_ref: Mapped[str | None] = mapped_column(String(1024))
    reconciliation_secret_ref: Mapped[str | None] = mapped_column(String(1024))
    delegated_subject: Mapped[str | None] = mapped_column(String(320))
    scopes: Mapped[list[str]] = mapped_column(JSON, default=list)
    status: Mapped[ConnectionStatus] = mapped_column(
        Enum(ConnectionStatus), default=ConnectionStatus.PENDING, nullable=False, index=True
    )
    rate_limit_per_minute: Mapped[int] = mapped_column(Integer, default=120, nullable=False)
    last_health_check_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_error: Mapped[str | None] = mapped_column(Text)
    authorized_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    organization: Mapped["Organization"] = relationship(back_populates="email_connections")


class SsoConnection(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "sso_connections"
    __table_args__ = (UniqueConstraint("organization_id", "provider", name="uq_org_sso_provider"),)

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    issuer: Mapped[str] = mapped_column(String(1024), nullable=False)
    client_id: Mapped[str] = mapped_column(String(255), nullable=False)
    client_secret_ref: Mapped[str | None] = mapped_column(String(1024))
    allowed_domains: Mapped[list[str]] = mapped_column(JSON, default=list)
    group_role_mappings: Mapped[dict] = mapped_column(JSON, default=dict)
    status: Mapped[ConnectionStatus] = mapped_column(
        Enum(ConnectionStatus), default=ConnectionStatus.PENDING, nullable=False
    )


class ScimCredential(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "scim_credentials"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    token_prefix: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    token_hash: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    description: Mapped[str] = mapped_column(String(255), default="SCIM provisioning token")
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)


class OidcTransaction(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "oidc_transactions"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    sso_connection_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("sso_connections.id"), nullable=False, index=True)
    state_hash: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    code_verifier: Mapped[str] = mapped_column(EncryptedString(1024), nullable=False)
    nonce: Mapped[str] = mapped_column(EncryptedString(1024), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class Role(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "roles"

    name: Mapped[UserRole] = mapped_column(Enum(UserRole), unique=True, nullable=False)

    users: Mapped[list["UserRoleLink"]] = relationship(back_populates="role")


class User(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "users"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    password_hash: Mapped[str] = mapped_column(String(512), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    mfa_enabled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    mfa_secret: Mapped[str | None] = mapped_column(EncryptedString(1024))
    mfa_recovery_hashes: Mapped[list[str]] = mapped_column(JSON, default=list)
    external_subject: Mapped[str | None] = mapped_column(String(255), index=True)

    organization: Mapped["Organization"] = relationship(back_populates="users")
    roles: Mapped[list["UserRoleLink"]] = relationship(back_populates="user", cascade="all, delete-orphan")
    employee_links: Mapped[list["Employee"]] = relationship(back_populates="portal_user")
    sessions: Mapped[list["AuthSession"]] = relationship(back_populates="user", cascade="all, delete-orphan")


class AuthSession(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "auth_sessions"

    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False, index=True)
    token_jti: Mapped[str] = mapped_column(String(128), unique=True, nullable=False, index=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    idle_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    csrf_token_hash: Mapped[str | None] = mapped_column(String(64))
    auth_method: Mapped[str] = mapped_column(String(32), default="password", nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)

    user: Mapped["User"] = relationship(back_populates="sessions")


class UserRoleLink(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "user_roles"
    __table_args__ = (UniqueConstraint("user_id", "role_id", name="uq_user_role"),)

    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    role_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("roles.id"), nullable=False)

    user: Mapped["User"] = relationship(back_populates="roles")
    role: Mapped["Role"] = relationship(back_populates="users")


class OrganizationInvitation(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "organization_invitations"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    invited_by_user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    email_ciphertext: Mapped[str] = mapped_column(EncryptedString(1024), nullable=False)
    email_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    invitee_name: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[UserRole] = mapped_column(Enum(UserRole), default=UserRole.ADMIN, nullable=False)
    token_public_id: Mapped[str] = mapped_column(String(32), unique=True, nullable=False, index=True)
    token_secret_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    accepted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)


class Department(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "departments"
    __table_args__ = (
        UniqueConstraint("organization_id", "directory_source", "external_id", name="uq_org_department_external"),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    code: Mapped[str] = mapped_column(String(64), nullable=False)
    directory_source: Mapped[str] = mapped_column(String(32), default="manual", nullable=False)
    external_id: Mapped[str | None] = mapped_column(String(255), index=True)

    organization: Mapped["Organization"] = relationship(back_populates="departments")
    employees: Mapped[list["Employee"]] = relationship(back_populates="department")


class Employee(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "employees"
    __table_args__ = (
        UniqueConstraint("organization_id", "employee_id", name="uq_org_employee_code"),
        UniqueConstraint("organization_id", "directory_source", "external_id", name="uq_org_employee_external"),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    department_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("departments.id"), index=True)
    portal_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    employee_id: Mapped[str] = mapped_column(String(64), nullable=False)
    full_name: Mapped[str] = mapped_column(EncryptedString(1024), nullable=False)
    email: Mapped[str] = mapped_column(EncryptedString(1024), nullable=False)
    email_blind_index: Mapped[str | None] = mapped_column(String(64), index=True)
    directory_source: Mapped[str] = mapped_column(String(32), default="manual", nullable=False)
    external_id: Mapped[str | None] = mapped_column(String(255), index=True)
    phone: Mapped[str | None] = mapped_column(EncryptedString(1024))
    role_title: Mapped[str] = mapped_column(String(255), nullable=False)
    approved_context_summary: Mapped[str | None] = mapped_column(EncryptedString(4096))
    approved_public_profile_summary: Mapped[str | None] = mapped_column(EncryptedString(4096))
    training_preferences: Mapped[list[str]] = mapped_column(JSON, default=list)
    consent_status: Mapped[ConsentStatus] = mapped_column(Enum(ConsentStatus), default=ConsentStatus.PENDING, index=True)
    risk_score: Mapped[int] = mapped_column(Integer, default=0)
    status: Mapped[EmployeeStatus] = mapped_column(Enum(EmployeeStatus), default=EmployeeStatus.ACTIVE, index=True)

    organization: Mapped["Organization"] = relationship(back_populates="employees")
    department: Mapped["Department"] = relationship(back_populates="employees")
    portal_user: Mapped["User | None"] = relationship(back_populates="employee_links")
    consent_records: Mapped[list["ConsentRecord"]] = relationship(back_populates="employee", cascade="all, delete-orphan")
    context_profiles: Mapped[list["ContextProfile"]] = relationship(back_populates="employee", cascade="all, delete-orphan")
    campaign_targets: Mapped[list["CampaignTarget"]] = relationship(back_populates="employee")
    training_assignments: Mapped[list["TrainingAssignment"]] = relationship(back_populates="employee")
    risk_scores: Mapped[list["RiskScore"]] = relationship(back_populates="employee")


class ConsentRecord(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "consent_records"

    employee_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("employees.id"), nullable=False, index=True)
    status: Mapped[ConsentStatus] = mapped_column(Enum(ConsentStatus), nullable=False)
    source: Mapped[str] = mapped_column(String(255), default="manual")
    note: Mapped[str | None] = mapped_column(Text)
    opt_out_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    redaction_requested_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    employee: Mapped["Employee"] = relationship(back_populates="consent_records")


class ContextProfile(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "context_profiles"

    employee_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("employees.id"), nullable=False, index=True)
    employee_context_profile: Mapped[str] = mapped_column(EncryptedString(8192), nullable=False)
    likely_scenario_themes: Mapped[list[str]] = mapped_column(JSON, default=list)
    allowed_channels: Mapped[list[str]] = mapped_column(JSON, default=list)
    sensitivity_tags: Mapped[list[str]] = mapped_column(JSON, default=list)

    employee: Mapped["Employee"] = relationship(back_populates="context_profiles")


class Policy(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "policies"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(255), default="Default policy")
    allowed_themes: Mapped[list[str]] = mapped_column(JSON, default=list)
    prohibited_words: Mapped[list[str]] = mapped_column(JSON, default=list)
    allowed_sender_names: Mapped[list[str]] = mapped_column(JSON, default=list)
    approved_training_domains: Mapped[list[str]] = mapped_column(JSON, default=list)
    allowed_delivery_channels: Mapped[list[str]] = mapped_column(JSON, default=list)
    difficulty_levels: Mapped[list[str]] = mapped_column(JSON, default=list)
    maximum_frequency_per_employee: Mapped[int] = mapped_column(Integer, default=2)
    working_hours_start: Mapped[int] = mapped_column(Integer, default=9)
    working_hours_end: Mapped[int] = mapped_column(Integer, default=18)
    second_approval_required: Mapped[bool] = mapped_column(Boolean, default=True)
    opt_out_respected: Mapped[bool] = mapped_column(Boolean, default=True)
    prohibited_topics: Mapped[list[str]] = mapped_column(JSON, default=list)

    versions: Mapped[list["PolicyVersion"]] = relationship(back_populates="policy", cascade="all, delete-orphan")


class PolicyVersion(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "policy_versions"

    policy_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("policies.id"), nullable=False, index=True)
    changed_by_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    snapshot: Mapped[dict] = mapped_column(JSON, nullable=False)

    policy: Mapped["Policy"] = relationship(back_populates="versions")


class FailureReason(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "failure_reasons"

    code: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)


class ImpersonationPersona(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A registered, consent-governed identity that voice and deepfake simulations may imitate.

    BreachSim never clones a real individual from scraped media. A persona is either a
    synthetic composite role (``is_real_person`` false) or a real employee who has signed
    an authorization on file, recorded here with an expiry so consent cannot go stale.
    """

    __tablename__ = "impersonation_personas"
    __table_args__ = (UniqueConstraint("organization_id", "reference_code", name="uq_org_persona_code"),)

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    approved_by_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))

    reference_code: Mapped[str] = mapped_column(String(64), nullable=False)
    display_name: Mapped[str] = mapped_column(String(255), nullable=False)
    role_title: Mapped[str] = mapped_column(String(255), nullable=False)
    relationship_to_targets: Mapped[str] = mapped_column(String(255), default="internal colleague")
    modality: Mapped[MediaModality] = mapped_column(Enum(MediaModality), default=MediaModality.VOICE_NOTE)
    status: Mapped[PersonaStatus] = mapped_column(Enum(PersonaStatus), default=PersonaStatus.DRAFT, index=True)

    is_real_person: Mapped[bool] = mapped_column(Boolean, default=False)
    linked_employee_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("employees.id"))
    consent_reference: Mapped[str | None] = mapped_column(String(255))
    consent_evidence_note: Mapped[str | None] = mapped_column(EncryptedString(4096))
    consent_granted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    consent_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revocation_reason: Mapped[str | None] = mapped_column(Text)

    #: Browser speech-synthesis hints so the simulator can render the persona voice locally
    #: when no cloning provider is configured (the zero-cost fallback path).
    voice_profile: Mapped[dict] = mapped_column(JSON, default=dict)
    #: Detection cues surfaced to the employee after the simulation resolves.
    detection_tells: Mapped[list[str]] = mapped_column(JSON, default=list)
    synthetic_disclosure_text: Mapped[str] = mapped_column(
        Text,
        default="Simulated synthetic media generated for authorized security awareness training.",
    )
    usage_count: Mapped[int] = mapped_column(Integer, default=0)

    #: Provider-side reference for this persona's cloned voice (e.g. an ElevenLabs
    #: voice_id), set once a consented sample has been enrolled.
    voice_clone_provider: Mapped[str | None] = mapped_column(String(64))
    voice_clone_ref: Mapped[str | None] = mapped_column(String(255))
    #: True once a consented face image is on file for talking-head video.
    has_face_image: Mapped[bool] = mapped_column(Boolean, default=False)

    media_assets: Mapped[list["MediaAsset"]] = relationship(
        back_populates="persona",
        cascade="all, delete-orphan",
        foreign_keys="MediaAsset.persona_id",
    )

    def is_usable(self, *, now: datetime | None = None) -> bool:
        """True when the persona is approved and its consent window is still open."""
        moment = now or datetime.now(timezone.utc)
        if self.status != PersonaStatus.APPROVED or self.revoked_at is not None:
            return False
        if self.consent_expires_at is None:
            return True
        expires_at = self.consent_expires_at
        if expires_at.tzinfo is None:
            expires_at = expires_at.replace(tzinfo=timezone.utc)
        return expires_at > moment


class MediaAsset(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A stored media artefact — a consented enrolment sample or a generated clip.

    Bytes live on disk under the media store; this row holds the metadata, the retention
    clock, and the provider reference. A generated clip is bound to the scenario version
    it was rendered for, so re-approving a scenario reuses its media rather than
    regenerating (and re-billing).
    """

    __tablename__ = "media_assets"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    persona_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("impersonation_personas.id"), index=True)
    scenario_version_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("scenario_versions.id"), index=True)
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))

    kind: Mapped[MediaAssetKind] = mapped_column(Enum(MediaAssetKind), nullable=False, index=True)
    status: Mapped[MediaAssetStatus] = mapped_column(Enum(MediaAssetStatus), default=MediaAssetStatus.READY, index=True)
    provider: Mapped[str | None] = mapped_column(String(64))
    provider_ref: Mapped[str | None] = mapped_column(String(255))

    content_type: Mapped[str] = mapped_column(String(128), default="application/octet-stream")
    #: Path relative to the media store root. Null while a render is still pending.
    storage_path: Mapped[str | None] = mapped_column(String(512))
    byte_size: Mapped[int] = mapped_column(Integer, default=0)
    #: SHA-256 of the stored bytes, so an asset's integrity can be shown in the audit trail.
    checksum: Mapped[str | None] = mapped_column(String(64))
    duration_ms: Mapped[int | None] = mapped_column(Integer)

    #: A single-use, unguessable token the simulator uses to stream this asset without auth.
    access_token: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    generation_detail: Mapped[dict] = mapped_column(JSON, default=dict)

    persona: Mapped["ImpersonationPersona | None"] = relationship(
        back_populates="media_assets", foreign_keys=[persona_id]
    )

    def is_available(self, *, now: datetime | None = None) -> bool:
        moment = now or datetime.now(timezone.utc)
        if self.status != MediaAssetStatus.READY or not self.storage_path:
            return False
        if self.expires_at is None:
            return True
        expires_at = self.expires_at if self.expires_at.tzinfo else self.expires_at.replace(tzinfo=timezone.utc)
        return expires_at > moment


class Scenario(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "scenarios"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    profile_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("context_profiles.id"))
    persona_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("impersonation_personas.id"), index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    channel: Mapped[Channel] = mapped_column(Enum(Channel), nullable=False)
    theme: Mapped[str] = mapped_column(String(255), nullable=False)
    difficulty_level: Mapped[DifficultyLevel] = mapped_column(Enum(DifficultyLevel), nullable=False)
    status: Mapped[ScenarioStatus] = mapped_column(Enum(ScenarioStatus), default=ScenarioStatus.DRAFT, index=True)
    current_version_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("scenario_versions.id"))
    approved_by_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    detected_persuasion_triggers: Mapped[list[str]] = mapped_column(JSON, default=list)
    policy_validation: Mapped[dict] = mapped_column(JSON, default=dict)

    versions: Mapped[list["ScenarioVersion"]] = relationship(
        back_populates="scenario",
        cascade="all, delete-orphan",
        foreign_keys="ScenarioVersion.scenario_id",
    )
    persona: Mapped["ImpersonationPersona | None"] = relationship(foreign_keys=[persona_id])


class ScenarioVersion(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "scenario_versions"

    scenario_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("scenarios.id"), nullable=False, index=True)
    version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    subject: Mapped[str] = mapped_column(String(255), nullable=False)
    body_copy: Mapped[str] = mapped_column(Text, nullable=False)
    cta_text: Mapped[str] = mapped_column(String(255), nullable=False)
    landing_page_copy: Mapped[str] = mapped_column(Text, nullable=False)
    rationale_metadata: Mapped[dict] = mapped_column(JSON, default=dict)
    detected_persuasion_triggers: Mapped[list[str]] = mapped_column(JSON, default=list)
    difficulty_score: Mapped[int] = mapped_column(Integer, default=30)
    validation_result: Mapped[dict] = mapped_column(JSON, default=dict)
    notes: Mapped[str | None] = mapped_column(Text)
    #: Channel-specific structured content: the branching call script for vishing, the
    #: impersonation brief for deepfake, the email/scan spec for QR. Empty for plain email.
    channel_payload: Mapped[dict] = mapped_column(JSON, default=dict)

    scenario: Mapped["Scenario"] = relationship(back_populates="versions", foreign_keys=[scenario_id])


class Campaign(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "campaigns"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    approved_by_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    second_approved_by_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    channel: Mapped[Channel] = mapped_column(Enum(Channel), nullable=False)
    campaign_type: Mapped[CampaignType] = mapped_column(Enum(CampaignType), default=CampaignType.ONE_TIME)
    status: Mapped[CampaignStatus] = mapped_column(Enum(CampaignStatus), default=CampaignStatus.DRAFT, index=True)
    schedule_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    throttling_per_hour: Mapped[int] = mapped_column(Integer, default=25)
    requires_second_approval: Mapped[bool] = mapped_column(Boolean, default=True)
    target_filters: Mapped[dict] = mapped_column(JSON, default=dict)
    sandbox_mode: Mapped[bool] = mapped_column(Boolean, default=True)
    learning_objective: Mapped[str] = mapped_column(String(255), default="Recognize social engineering patterns.")
    landing_domain_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("organization_domains.id"), index=True)
    email_connection_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("email_connections.id"), index=True)

    targets: Mapped[list["CampaignTarget"]] = relationship(back_populates="campaign", cascade="all, delete-orphan")
    scenario_links: Mapped[list["CampaignScenario"]] = relationship(back_populates="campaign", cascade="all, delete-orphan")
    delivery_attempts: Mapped[list["DeliveryAttempt"]] = relationship(back_populates="campaign")
    events: Mapped[list["EventLog"]] = relationship(back_populates="campaign")
    runs: Mapped[list["CampaignRun"]] = relationship(back_populates="campaign")


class CampaignRun(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "campaign_runs"
    __table_args__ = (
        UniqueConstraint("organization_id", "idempotency_key", name="uq_org_campaign_run_idempotency"),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    campaign_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("campaigns.id"), nullable=False, index=True)
    created_by_user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    idempotency_key: Mapped[str] = mapped_column(String(128), nullable=False)
    status: Mapped[CampaignRunStatus] = mapped_column(
        Enum(CampaignRunStatus), default=CampaignRunStatus.QUEUED, nullable=False, index=True
    )
    scenario_snapshot: Mapped[dict] = mapped_column(JSON, nullable=False)
    policy_snapshot: Mapped[dict] = mapped_column(JSON, nullable=False)
    branding_snapshot: Mapped[dict] = mapped_column(JSON, nullable=False)
    delivery_snapshot: Mapped[dict] = mapped_column(JSON, nullable=False)
    reporting_identity_mode: Mapped[ReportingIdentityMode] = mapped_column(
        Enum(ReportingIdentityMode), default=ReportingIdentityMode.PSEUDONYMOUS, nullable=False
    )
    scheduled_for: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    target_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    queued_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    processing_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    accepted_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    bounced_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    suppressed_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    failed_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    unknown_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    campaign: Mapped["Campaign"] = relationship(back_populates="runs")
    attempts: Mapped[list["DeliveryAttempt"]] = relationship(back_populates="campaign_run")


class CampaignTarget(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "campaign_targets"

    campaign_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("campaigns.id"), nullable=False, index=True)
    employee_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("employees.id"), nullable=False, index=True)
    target_group_label: Mapped[str | None] = mapped_column(String(255))

    campaign: Mapped["Campaign"] = relationship(back_populates="targets")
    employee: Mapped["Employee"] = relationship(back_populates="campaign_targets")


class CampaignScenario(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "campaign_scenarios"

    campaign_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("campaigns.id"), nullable=False, index=True)
    scenario_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("scenarios.id"), nullable=False, index=True)

    campaign: Mapped["Campaign"] = relationship(back_populates="scenario_links")
    scenario: Mapped["Scenario"] = relationship()


class DeliveryAttempt(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "delivery_attempts"
    __table_args__ = (
        UniqueConstraint("campaign_run_id", "employee_id", name="uq_run_employee_attempt"),
    )

    campaign_run_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("campaign_runs.id"), index=True)
    campaign_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("campaigns.id"), nullable=False, index=True)
    employee_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("employees.id"), nullable=False, index=True)
    scenario_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("scenarios.id"))
    channel: Mapped[Channel] = mapped_column(Enum(Channel), nullable=False, index=True)
    status: Mapped[DeliveryStatus] = mapped_column(Enum(DeliveryStatus), default=DeliveryStatus.SANDBOXED)
    sandbox_mode: Mapped[bool] = mapped_column(Boolean, default=True)
    preview_payload: Mapped[dict] = mapped_column(JSON, default=dict)
    provider_message_id: Mapped[str | None] = mapped_column(String(255))
    delivered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    recipient_ciphertext: Mapped[str | None] = mapped_column(EncryptedString(1024))
    idempotency_key: Mapped[str | None] = mapped_column(String(128), unique=True, index=True)
    retry_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    next_attempt_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    last_error_code: Mapped[str | None] = mapped_column(String(128))
    last_error_detail: Mapped[str | None] = mapped_column(Text)
    accepted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    bounced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    campaign: Mapped["Campaign"] = relationship(back_populates="delivery_attempts")
    campaign_run: Mapped["CampaignRun | None"] = relationship(back_populates="attempts")


class LandingToken(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "landing_tokens"

    delivery_attempt_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("delivery_attempts.id"), nullable=False, index=True)
    employee_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("employees.id"), nullable=False, index=True)
    campaign_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("campaigns.id"), nullable=False, index=True)
    token: Mapped[str | None] = mapped_column(String(255), unique=True)
    token_public_id: Mapped[str | None] = mapped_column(String(32), unique=True, index=True)
    token_secret_hash: Mapped[str | None] = mapped_column(String(64))
    token_secret_ciphertext: Mapped[str | None] = mapped_column(EncryptedString(1024))
    landing_hostname: Mapped[str | None] = mapped_column(String(253), index=True)
    landing_type: Mapped[str] = mapped_column(String(64), nullable=False)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    first_scanned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)


class QrAssetToken(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "qr_asset_tokens"

    landing_token_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("landing_tokens.id"), nullable=False, index=True)
    public_id: Mapped[str] = mapped_column(String(32), unique=True, nullable=False, index=True)
    secret_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    secret_ciphertext: Mapped[str | None] = mapped_column(EncryptedString(1024))
    qr_payload_ciphertext: Mapped[str] = mapped_column(EncryptedString(4096), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)


class OutboxEvent(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "outbox_events"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    aggregate_type: Mapped[str] = mapped_column(String(64), nullable=False)
    aggregate_id: Mapped[uuid.UUID] = mapped_column(nullable=False, index=True)
    event_type: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    payload: Mapped[dict] = mapped_column(JSON, nullable=False)
    status: Mapped[OutboxStatus] = mapped_column(
        Enum(OutboxStatus), default=OutboxStatus.PENDING, nullable=False, index=True
    )
    available_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False, index=True
    )
    publish_attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_error: Mapped[str | None] = mapped_column(Text)


class DeliverySuppression(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "delivery_suppressions"
    __table_args__ = (UniqueConstraint("organization_id", "email_hash", name="uq_org_suppression_email"),)

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    email_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    reason: Mapped[SuppressionReason] = mapped_column(Enum(SuppressionReason), nullable=False)
    provider: Mapped[EmailProviderKind | None] = mapped_column(Enum(EmailProviderKind))
    active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False, index=True)
    details: Mapped[dict] = mapped_column(JSON, default=dict)


class ProviderEventReceipt(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "provider_event_receipts"
    __table_args__ = (
        UniqueConstraint("email_connection_id", "provider_event_id", name="uq_connection_provider_event"),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    email_connection_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("email_connections.id"), nullable=False, index=True)
    delivery_attempt_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("delivery_attempts.id"), nullable=False, index=True)
    provider_event_id: Mapped[str] = mapped_column(String(255), nullable=False)
    payload_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    reconciled_status: Mapped[DeliveryStatus] = mapped_column(Enum(DeliveryStatus), nullable=False)
    reason_code: Mapped[str | None] = mapped_column(String(128))
    signature_timestamp: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class EventLog(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "event_logs"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    employee_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("employees.id"), index=True)
    campaign_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("campaigns.id"), index=True)
    delivery_attempt_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("delivery_attempts.id"), index=True)
    landing_token_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("landing_tokens.id"))
    event_type: Mapped[EventType] = mapped_column(Enum(EventType), nullable=False, index=True)
    channel: Mapped[Channel | None] = mapped_column(Enum(Channel))
    event_metadata: Mapped[dict] = mapped_column(JSON, default=dict)
    pseudo_event_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    campaign: Mapped["Campaign | None"] = relationship(back_populates="events")


class SimulationResponse(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Step-level evidence from an interactive simulation (voice call or synthetic media).

    Email and QR produce a single click event; a vishing or deepfake simulation is a
    conversation. Each decision the employee makes is stored here so the campaign report
    can show *where* in the pressure sequence the person complied or verified.
    """

    __tablename__ = "simulation_responses"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    employee_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("employees.id"), nullable=False, index=True)
    campaign_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("campaigns.id"), index=True)
    delivery_attempt_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("delivery_attempts.id"), index=True)
    landing_token_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("landing_tokens.id"))
    event_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("event_logs.id"))

    channel: Mapped[Channel] = mapped_column(Enum(Channel), nullable=False, index=True)
    step_index: Mapped[int] = mapped_column(Integer, default=0)
    step_key: Mapped[str] = mapped_column(String(64), nullable=False)
    step_prompt: Mapped[str] = mapped_column(Text, default="")
    response_key: Mapped[str] = mapped_column(String(64), nullable=False)
    response_label: Mapped[str] = mapped_column(Text, default="")
    is_safe_action: Mapped[bool] = mapped_column(Boolean, default=False, index=True)
    risk_weight: Mapped[int] = mapped_column(Integer, default=0)
    elapsed_ms: Mapped[int] = mapped_column(Integer, default=0)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class TrainingModule(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "training_modules"

    organization_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("organizations.id"))
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    vector: Mapped[str] = mapped_column(String(64), nullable=False)
    primary_reason_code: Mapped[str] = mapped_column(String(64), nullable=False)
    duration_seconds: Mapped[int] = mapped_column(Integer, default=45)
    guidance_points: Mapped[list[str]] = mapped_column(JSON, default=list)
    body: Mapped[str] = mapped_column(Text, nullable=False)

    assignments: Mapped[list["TrainingAssignment"]] = relationship(back_populates="module")


class TrainingAssignment(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "training_assignments"

    employee_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("employees.id"), nullable=False, index=True)
    module_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("training_modules.id"), nullable=False)
    campaign_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("campaigns.id"))
    source_event_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("event_logs.id"))
    status: Mapped[TrainingAssignmentStatus] = mapped_column(
        Enum(TrainingAssignmentStatus),
        default=TrainingAssignmentStatus.ASSIGNED,
    )
    assigned_reason_codes: Mapped[list[str]] = mapped_column(JSON, default=list)
    retest_scheduled_for: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    employee: Mapped["Employee"] = relationship(back_populates="training_assignments")
    module: Mapped["TrainingModule"] = relationship(back_populates="assignments")
    completions: Mapped[list["TrainingCompletion"]] = relationship(back_populates="assignment", cascade="all, delete-orphan")


class TrainingCompletion(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "training_completions"

    assignment_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("training_assignments.id"), nullable=False, index=True)
    employee_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("employees.id"), nullable=False, index=True)
    dwell_seconds: Mapped[int] = mapped_column(Integer, default=30)
    completed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    assignment: Mapped["TrainingAssignment"] = relationship(back_populates="completions")


class RiskScore(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "risk_scores"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    employee_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("employees.id"), index=True)
    department_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("departments.id"), index=True)
    channel: Mapped[Channel | None] = mapped_column(Enum(Channel))
    score: Mapped[int] = mapped_column(Integer, nullable=False)
    reason_breakdown: Mapped[dict] = mapped_column(JSON, default=dict)
    calculated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    employee: Mapped["Employee | None"] = relationship(back_populates="risk_scores")


class AuditLog(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "audit_logs"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"), index=True)
    action: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    resource_type: Mapped[str] = mapped_column(String(255), nullable=False)
    resource_id: Mapped[str | None] = mapped_column(String(255))
    details: Mapped[dict] = mapped_column(JSON, default=dict)
    previous_hash: Mapped[str | None] = mapped_column(String(64))
    entry_hash: Mapped[str | None] = mapped_column(String(64), unique=True, index=True)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class AccessLog(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "access_logs"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    resource_type: Mapped[str] = mapped_column(String(255), nullable=False)
    resource_id: Mapped[str] = mapped_column(String(255), nullable=False)
    action: Mapped[str] = mapped_column(String(64), default="read")
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class ReportExport(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "report_exports"

    organization_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("organizations.id"), nullable=False, index=True)
    generated_by_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
    report_type: Mapped[str] = mapped_column(String(128), nullable=False)
    format: Mapped[str] = mapped_column(String(32), nullable=False)
    path: Mapped[str] = mapped_column(String(512), nullable=False)
    filters: Mapped[dict] = mapped_column(JSON, default=dict)
