from __future__ import annotations

from collections.abc import Generator

from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

from app.core.config import settings
from app.db.base import Base

connect_args = {"check_same_thread": False} if settings.database_url.startswith("sqlite") else {}
engine = create_engine(settings.database_url, future=True, connect_args=connect_args)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False, future=True)


def ensure_schema_compatibility() -> None:
    if not settings.database_url.startswith("sqlite"):
        return

    required_columns = {
        "organizations": {
            "email_provider_enabled": "INTEGER NOT NULL DEFAULT 0",
            "email_provider_mode": "VARCHAR(32) NOT NULL DEFAULT 'sandbox'",
            "smtp_host": "VARCHAR(255)",
            "smtp_port": "INTEGER NOT NULL DEFAULT 587",
            "smtp_username": "VARCHAR(255)",
            "smtp_password": "TEXT",
            "smtp_from_email": "VARCHAR(255)",
            "smtp_sender_name": "VARCHAR(255)",
            "smtp_recipient_allowlist": "JSON",
            "sms_provider_enabled": "INTEGER NOT NULL DEFAULT 0",
            "sms_provider_mode": "VARCHAR(32) NOT NULL DEFAULT 'sandbox'",
            "sms_api_base_url": "VARCHAR(512)",
            "sms_account_sid": "VARCHAR(255)",
            "sms_auth_token": "TEXT",
            "sms_from_number": "VARCHAR(64)",
            "sms_recipient_allowlist": "JSON",
            "voice_provider_enabled": "INTEGER NOT NULL DEFAULT 0",
            "voice_provider_mode": "VARCHAR(32) NOT NULL DEFAULT 'simulator'",
            "voice_api_base_url": "VARCHAR(512)",
            "voice_account_sid": "VARCHAR(255)",
            "voice_auth_token": "TEXT",
            "voice_from_number": "VARCHAR(64)",
            "voice_recipient_allowlist": "JSON",
            "impersonation_enabled": "INTEGER NOT NULL DEFAULT 0",
            "impersonation_disclosure_text": "TEXT",
        },
        "scenarios": {
            "persona_id": "CHAR(32)",
        },
        "scenario_versions": {
            "channel_payload": "JSON",
        },
        "impersonation_personas": {
            "voice_clone_provider": "VARCHAR(64)",
            "voice_clone_ref": "VARCHAR(255)",
            "has_face_image": "INTEGER NOT NULL DEFAULT 0",
        },
    }

    # ALTER TABLE ADD COLUMN leaves existing rows NULL, and a SQLAlchemy `default=`
    # only fires on ORM insert. Backfill anything the response models require to be
    # non-null so upgrading an existing database does not 500 on first read.
    column_backfills = {
        "organizations": {
            "smtp_recipient_allowlist": "[]",
            "sms_recipient_allowlist": "[]",
            "voice_recipient_allowlist": "[]",
            "impersonation_disclosure_text": (
                "Simulated synthetic media generated by BreachSim for authorized security "
                "awareness training. No real person was recorded, cloned, or published."
            ),
        },
        "scenario_versions": {
            "channel_payload": "{}",
        },
    }

    with engine.begin() as connection:
        tables = {
            row[0]
            for row in connection.exec_driver_sql(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).all()
        }
        for table_name, columns in required_columns.items():
            if table_name not in tables:
                continue
            existing_columns = {
                row[1] for row in connection.exec_driver_sql(f"PRAGMA table_info({table_name})").all()
            }
            for column_name, definition in columns.items():
                if column_name in existing_columns:
                    continue
                connection.exec_driver_sql(
                    f"ALTER TABLE {table_name} ADD COLUMN {column_name} {definition}"
                )
            for column_name, fallback in column_backfills.get(table_name, {}).items():
                if column_name not in existing_columns and column_name not in columns:
                    continue
                connection.exec_driver_sql(
                    f"UPDATE {table_name} SET {column_name} = ? WHERE {column_name} IS NULL",
                    (fallback,),
                )


def get_db() -> Generator[Session, None, None]:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db() -> None:
    from app.models import entities  # noqa: F401
    from app.services.seed import seed_database

    Base.metadata.create_all(bind=engine)
    ensure_schema_compatibility()
    db = SessionLocal()
    try:
        seed_database(db)
    finally:
        db.close()
