"""voice and deepfake impersonation channels

Adds the deepfake channel, interactive-simulation event types, the consent-governed
impersonation persona registry, step-level simulation evidence, and the SMS/voice
provider configuration block.

Revision ID: 20260727_0002
Revises: 20260317_0001
Create Date: 2026-07-27 10:00:00
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from app.db.base import Base
from app.models import entities  # noqa: F401

revision = "20260727_0002"
down_revision = "20260317_0001"
branch_labels = None
depends_on = None


NEW_CHANNEL_VALUES = ("deepfake",)

NEW_EVENT_TYPE_VALUES = (
    "replied_sms",
    "answered_call",
    "disclosed_on_call",
    "verified_caller",
    "ended_call_safely",
    "played_synthetic_media",
    "trusted_synthetic_media",
    "flagged_synthetic_media",
    "verified_out_of_band",
)

NEW_TABLES = ("impersonation_personas", "simulation_responses")

def new_columns() -> dict[str, list[sa.Column]]:
    """Fresh Column objects per call — a Column cannot be attached to two tables."""
    return {
    "organizations": [
        sa.Column("sms_provider_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("sms_provider_mode", sa.String(32), nullable=False, server_default="sandbox"),
        sa.Column("sms_api_base_url", sa.String(512), nullable=True),
        sa.Column("sms_account_sid", sa.String(255), nullable=True),
        sa.Column("sms_auth_token", sa.String(1024), nullable=True),
        sa.Column("sms_from_number", sa.String(64), nullable=True),
        sa.Column("sms_recipient_allowlist", sa.JSON(), nullable=True),
        sa.Column("voice_provider_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("voice_provider_mode", sa.String(32), nullable=False, server_default="simulator"),
        sa.Column("voice_api_base_url", sa.String(512), nullable=True),
        sa.Column("voice_account_sid", sa.String(255), nullable=True),
        sa.Column("voice_auth_token", sa.String(1024), nullable=True),
        sa.Column("voice_from_number", sa.String(64), nullable=True),
        sa.Column("voice_recipient_allowlist", sa.JSON(), nullable=True),
        sa.Column("impersonation_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("impersonation_disclosure_text", sa.Text(), nullable=True),
    ],
    "scenarios": [
        sa.Column("persona_id", sa.Uuid(), nullable=True),
    ],
    "scenario_versions": [
        sa.Column("channel_payload", sa.JSON(), nullable=True),
    ],
    }


def _existing_columns(inspector: sa.Inspector, table: str) -> set[str]:
    if table not in inspector.get_table_names():
        return set()
    return {column["name"] for column in inspector.get_columns(table)}


def _extend_pg_enum(bind: sa.engine.Connection, enum_name: str, values: tuple[str, ...]) -> None:
    """Postgres native enums need explicit value additions; other dialects use VARCHAR."""
    if bind.dialect.name != "postgresql":
        return
    for value in values:
        bind.execute(sa.text(f"ALTER TYPE {enum_name} ADD VALUE IF NOT EXISTS '{value}'"))


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Enum values must land before any column referencing them is written to.
    with op.get_context().autocommit_block():
        _extend_pg_enum(bind, "channel", NEW_CHANNEL_VALUES)
        _extend_pg_enum(bind, "eventtype", NEW_EVENT_TYPE_VALUES)

    for table_name, columns in new_columns().items():
        if table_name not in inspector.get_table_names():
            continue
        present = _existing_columns(inspector, table_name)
        for column in columns:
            if column.name in present:
                continue
            op.add_column(table_name, column)

    # create_all is checkfirst by default, so this only materializes the new tables
    # (plus their personastatus / mediamodality enum types).
    Base.metadata.create_all(bind=bind, tables=[Base.metadata.tables[name] for name in NEW_TABLES])

    # ADD COLUMN leaves existing rows NULL; backfill anything the API requires non-null.
    op.execute("UPDATE organizations SET sms_recipient_allowlist = '[]' WHERE sms_recipient_allowlist IS NULL")
    op.execute("UPDATE organizations SET voice_recipient_allowlist = '[]' WHERE voice_recipient_allowlist IS NULL")
    op.execute("UPDATE scenario_versions SET channel_payload = '{}' WHERE channel_payload IS NULL")
    op.execute(
        "UPDATE organizations SET impersonation_disclosure_text = "
        "'Simulated synthetic media generated by BreachSim for authorized security awareness "
        "training. No real person was recorded, cloned, or published.' "
        "WHERE impersonation_disclosure_text IS NULL"
    )


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    for table_name in reversed(NEW_TABLES):
        if table_name in inspector.get_table_names():
            op.drop_table(table_name)

    for table_name, columns in new_columns().items():
        if table_name not in inspector.get_table_names():
            continue
        present = _existing_columns(inspector, table_name)
        for column in columns:
            if column.name in present:
                op.drop_column(table_name, column.name)

    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS personastatus")
        op.execute("DROP TYPE IF EXISTS mediamodality")
    # Enum *values* added to channel / eventtype are intentionally left in place:
    # Postgres cannot remove a single label from an existing type without a full rebuild.
